# Generated by Django 4.2.7 on 2024-08-01 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrecord',
            name='author',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webpage',
            name='email',
            field=models.EmailField(default='naga@gmail.com', max_length=254),
        ),
    ]
